color: null
fieldLayouts:
  206875a8-9fdb-4cab-a9e9-2ce621dc5993:
    cardView:
      - 'layoutElement:ce6cc74c-e31b-4be8-a26b-f967279d9186'
      - 'layoutElement:4837b2d7-105a-42bc-b7df-e34fc612501b'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-23T12:57:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e242b1b-a836-40d1-8d03-3fa683c33ad4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T13:00:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bfb6dd1e-9068-42ec-946b-f49b2c699667 # Vinyl artist
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce6cc74c-e31b-4be8-a26b-f967279d9186
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T13:00:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4079dc7d-a87a-4567-8052-0e0bbdb74fb5 # Vinyl cover image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fac13c70-7c06-4a7c-a426-5896f895a07d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T13:00:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 00c4505d-a3ff-4b5a-8ab6-51633a754514 # Vinyl status
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4837b2d7-105a-42bc-b7df-e34fc612501b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T14:48:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6063994b-ceff-4c98-992b-89bb1b6f198c # Vinyl year
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce643068-7132-472a-8fc1-e48f2157844b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T14:48:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b883a2fc-876a-4a15-9b3e-43b004529b5f # Vinyl label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dffa4176-9f1e-4d0b-94e2-a13c8d170e81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T14:48:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 79db34d0-53e2-480e-b239-efe941831a2c # Vinyl tracklist
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57eb426f-c4e2-4c1b-b722-48cb023de4a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-23T14:48:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2e7c80fe-da4c-4367-a048-04f50462e1a4 # Discogs release ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 050ef72f-5b9c-4db7-8588-4b974de9433a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 811bac0c-df2c-4e5f-b98c-ae4598a07356
        userCondition: null
handle: vinyl
hasTitleField: true
icon: compact-disc
name: Vinyl
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
