altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fbee608b-5076-44ff-bc8d-8d34c1658043:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-25T08:05:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b42d15b9-f5b5-485e-895a-4bd4fe212ac9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-09-27T08:03:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c8d0a4d2-15dc-43b3-96b7-bc7acdc98fd5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 264b3442-e973-4c7f-b05c-984ec3897220
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: originals
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: /transforms/
