columnSuffix: null
handle: accordionBlocks
instructions: null
name: 'Accordion blocks'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 1b8e1298-21e1-4747-ac15-890cf7319601 # Accordion block
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
