defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 63fcea28-a867-4cfa-b68f-5982694c2d06 # Vinyl
handle: vinyls
maxAuthors: 1
name: Vinyls
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b43bcddf-8cc3-4971-b8ef-c4efe4bce91e: # Default
    enabledByDefault: true
    hasUrls: true
    template: _sections/vinyls/entry.twig
    uriFormat: 'vinyls/{slug}'
type: channel
